postgres_dsn: "postgres://username:password@postgres:5432/db-news-feeder?sslmode=disable"
migration_path: ./migrations
privileged_tokens:
  token-1: client-1
worker:
  interval: 5
  url_sources:
    - http://feeds.bbci.co.uk/news/uk/rss.xml 
    - http://feeds.bbci.co.uk/news/technology/rss.xml 
    - http://feeds.skynews.com/feeds/rss/uk.xml
    - http://feeds.skynews.com/feeds/rss/technology.xml
social:
  twitter:
    consumer_key: xxxx
    consumer_secret: xxxx
    access_token: xxxx
    access_secret: xxxxx