# to have this run first time around, please run go mod vendor first :)
version: '3.4'
services:
  postgres:
    image: postgres:10.17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-news-feeder
    ports:
      - 5432:5432
  api:
    container_name: "news-feeder-api"
    command: s
    build:
      context: .
    volumes:
      - .:/go/src/github.com/jeffreyyong/news-feeder
    ports:
      - 8080:8080
    tty: true
    restart: on-failure
    depends_on:
      - postgres
  worker:
    container_name: "news-feeder-worker"
    command: w
    build:
      context: .
    volumes:
      - .:/go/src/github.com/jeffreyyong/news-feeder
    ports:
      - 8081:8081
    tty: true
    restart: on-failure
    depends_on:
      - postgres
